name: avocado
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_auth: ^0.18.4+1
  firebase_core: any
  firebase_dynamic_links: any

  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.1+3
  firebase_storage: ^5.0.0
  image_cropper: 1.0.2
  image_picker: ^0.6.7+21
  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/
